### ISSUE TITLE
Dot at the end of error message with directory path is misleading

### ISSUE THREAD

**Issue by georgik** [esp-rs/espup#15]
Please, remove "." from the error messages where it contains the path to the directory.
It's slightly misleading when the user wants to copy and paste the path.

```
Previous installation of LLVM exist in: /home/rust/.espressif/tools/xtensa-esp32-elf-clang/esp-14.0.0-20220415-x86_64-unknown-linux-gnu.
```

**Comment by SergioGasquez** [comment]
Thanks for reporting it, I agree it's a bit confusing, do you think the following is clear enough?
```
Previous installation of LLVM exist in: '/home/rust/.espressif/tools/xtensa-esp32-elf-clang/esp-14.0.0-20220415-x86_64-unknown-linux-gnu'.
```
On another note, I don't think we should be bailing when there is an LLVM installed, instead, we should warn the user that we are reusing that installation and continue.
