### ISSUE TITLE
Change default location for ESP-IDF clone to `~/.espressif/frameworks/esp-idf...`

### ISSUE THREAD

**Issue by georgik** [esp-rs/espup#16]
Change default location for ESP-IDF clone to `~/.espressif/frameworks/esp-idf...`
This directory structure is already used in Windows and makes it easier to separate the esp-idf instance from the rest of the tools.

Right now, the implementation deployed to different directory:
```
~/.espressif/esp-idf-ae062fbba3ded0aa/v4.4.1/
```
Command
```
./espup install -e v4.4.1
```

**Comment by SergioGasquez** [comment]
Since we are using [`embuild`](https://github.com/esp-rs/embuild) for esp-idf installation, the directory structure is the same that is being used there, see this 3 functions: https://github.com/esp-rs/embuild/blob/master/src/espidf.rs#L323-L395.
