### ISSUE TITLE
build lvgl-rs in riscv32imc-esp-espidf target

### ISSUE THREAD

**Issue by imxood** [esp-rs/espup#192]
### How can i build the lvgl project?

![image](https://user-images.githubusercontent.com/14890680/221206531-0c9cf997-3096-472b-a02b-65fc8cc949bf.png)

- Would you like to implement this feature? [y/n]

**Comment by SergioGasquez** [comment]
Hi! I will be closing the issue as it is not related to `espup`, I strongly recommend you to join our matrix channel https://matrix.to/#/!LdaNPfUfvefOLewEIM:matrix.org?via=matrix.org&via=tchncs.de&via=envs.net and ask those types of questions there as they don't belong in any repo.
