### ISSUE TITLE
CLI option --esp-idf-version missing in v0.3.0, alternative not working

### ISSUE THREAD

**Issue by rand12345** [esp-rs/espup#193]
## Bug description

Upgraded from 0.2.8 and my build scripts failed. Substituting what I think is the correct option fails.

## To Reproduce

1. ... cargo install espup
2. ... espup install -v release/v4.4 

`$ espup install -v release/v4.4
error: invalid value 'release/v4.4' for '--toolchain-version <TOOLCHAIN_VERSION>': ⛔  Invalid toolchain version 'release/v4.4'. Verify that the format is correct: '<major>.<minor>.<patch>.<subpatch>' or '<major>.<minor>.<patch>', and that the release exists in https://github.com/esp-rs/rust-build/releases`

Rolling back to v0.2.8 works fine using `espup install --esp-idf-version release/v4.4`. Do I have the wrong option here or is there a breaking change in the naming convention of releases?

**Comment by SergioGasquez** [comment]
Hi @rand12345!

`espup` no longer installs `esp-idf`, you can see the full discussion in #154 and https://github.com/esp-rs/espup/pull/182, but basically we agreed on delegating to `esp-idf-sys` the `esp-idf` installation to remove duplicated code and avoid confusion on the users.
