### ISSUE TITLE
Frequest failures in Github Actions

### ISSUE THREAD

**Issue by bugadani** [esp-rs/espup#214]
Sometimes my GHA runs fail with the following error message:
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { error: GithubQuery, total_delay: 500ms, tries: 6 }', src/toolchain/mod.rs:165:6`

I imagine that if something fails twice in a row in 100ms, it won't likely succeed in the next .3s either. What would you think of
 - increasing the retry count a bit and
 - moving to exponential backoff?

**Comment by SergioGasquez** [comment]
Hi!
A few questions:
- Are you using `[xtensa-toolchain`](https://github.com/esp-rs/xtensa-toolchain) action?  Github queries usually fail in CI if `GITHUB_TOKEN` is not defined, see https://github.com/esp-rs/xtensa-toolchain#environment for more details
- Is, by any chance, the repo where you see this error public?

As you mention, maybe the retry strategy is not the best, I'll have a deeper look at your suggestions.

**Comment by bugadani** [comment]
No, I am not using xtensa-toolchain. I have the espup binary cached and I `espup install` during each of my CI runs. Though, maybe I could cache whatever espup installs, too, but that's a bit of a tangent here.

Sorry, the repo is private. "Frequent" might be an overstatement on my part. Thanks for the `GITHUB_TOKEN` suggestion, I don't think I might indeed want to set that.

**Comment by SergioGasquez** [comment]
Is there any reason why you don't want to add `GITHUB_TOKEN` and/or use `xtensa-toolchain`?

Regarding updating the Readme, I think it is a good idea to add a section explaining how to use `espup` in CI, thanks for the suggestion!

**Comment by bugadani** [comment]
> Is there any reason why you don't want to add GITHUB_TOKEN

Oh my, that was a bad slip of the finger on my part. I wanted to say that I want to do it, and I have done it since then.

**Comment by SergioGasquez** [comment]
> Oh my, that was a bad slip of the finger on my part. I wanted to say that I want to do it, and I have done it since then.

Great, I'll close this issue since the error should now disappear, but feel free to reopen this issue if it reappears. Here is some more information about the issue https://github.com/esp-rs/xtensa-toolchain/issues/15.

**Comment by bugadani** [comment]
Thanks!

**Comment by SergioGasquez** [comment]
Just added a small note to clarify this: https://github.com/esp-rs/espup/commit/ef483edf2799e665cc2af1fc0ac231598c8e1f11
