### ISSUE TITLE
espup is not able to update using just different build version

### ISSUE THREAD

**Issue by georgik** [esp-rs/espup#300]
Perform installation: `espup install --toolchain-version 1.71.0.0`

Perform update: `espup install --toolchain-version 1.71.0.1`

Incorrect result: Previous installation of Xtensa Rust 1.71.0 exists in: '/Users/georgik/.rustup/toolchains/esp'. Reusing this installation.

Expected result: espup updates the toolchain to 1.71.0.1

Workaround:
```
espup uninstall
espup install --toolchain-version 1.71.0.1
```

**Comment by SergioGasquez** [comment]
I was able to reproduce it with last released version, just checked and the PR is merged (https://github.com/esp-rs/espup/pull/272) but not yet released, I will do a release once  https://github.com/esp-rs/espup/pull/285 is merged
