### ISSUE TITLE
espup silently discards errors when /bin/bash is not available

### ISSUE THREAD

**Issue by knightpp** [esp-rs/espup#310]
## Bug description

Rust default installer https://github.com/esp-rs/rust/blob/4ca000ac85a4f486ed080c281c86ea2287592027/src/tools/rust-installer/install-template.sh#L1 uses `#!/bin/bash` shebang which is not available on some systems, but `espup` discards the script's output here https://github.com/esp-rs/espup/blob/d4870a5ad50d56a6d06695c6c64bdb0ce8e0eba6/src/toolchain/rust.rs#L238-L241 and here https://github.com/esp-rs/espup/blob/d4870a5ad50d56a6d06695c6c64bdb0ce8e0eba6/src/toolchain/rust.rs#L266-L269
so the installation reports itself as successful, but the actual rust toolchain won't be installed. In other words, there's no `~/.rustup/toolchains/esp/bin` folder.

Trying to use such incomplete installation leads to issues like https://github.com/esp-rs/rust-build/wiki/Build-failures#linux-x86_64. 

- Would you like to work on a fix? idk

## To Reproduce

1. Use system without `/bin/bash` or remove it
2. run `espup install`
3. the script will try to install rust compiler while silently discarding the error

## Expected behavior
The rust compiler installer script works in environments without `/bin/bash`.

## Environment

- OS: NixOS 23.05
- espup version: 0.4.1

**Comment by knightpp** [comment]
The shebang can probably be ignored by removing `-c` argument. Haven't tested yet.
```diff
+ .args(["bash"].chain(arguments)) 
- .args(["bash", "-c", &arguments]) 
```

**Comment by SergioGasquez** [comment]
Hi! Thanks for reporting and checking the fix! Would you like to open a PR with the fixing patch? If not, I am happy to open it

**Comment by knightpp** [comment]
> Would you like to open a PR with the fixing patch?

Hi. I'll be unavailable for some time today. Feel free to create PR.

**Comment by SergioGasquez** [comment]
Just created #312, could you verify that the PR works for you?
```
cargo uninstall espup
cargo install espup --git https://github.com/SergioGasquez/espup --branch fix/shebang
espup install
```

**Comment by knightpp** [comment]
It does not work. I added a comment to your PR.

**Comment by SergioGasquez** [comment]
> It does not work. I added a comment to your PR.

Thanks for your feedback, just addressed your comment and also added checking the result of the command, if it fails it will return the error! Do you mind trying it?

**Comment by knightpp** [comment]
It works! Thanks.
