### ISSUE TITLE
Documentation in README.MD espup install --esp-idf-version <ESP_IDF_VERSION> wrong

### ISSUE THREAD

**Issue by taunusflieger** [esp-rs/espup#67]
## Bug description

In the README.MD it is stated to use espup install --esp-idf-version <ESP_IDF_VERSION> to install. The parameter --esp-idf-version is wrong it should read --espidf-version. The correct command should be install --espidf-version <ESP_IDF_VERSION>

**Comment by SergioGasquez** [comment]
Hi! Thanks for opening the issue. The argument was changed, so if you are looking at the documentation of `master` branch you will see the updated argument. In the [`v.0.2.1` tag (which I suppose is the version you are using) is as `--espidf-version`](https://github.com/esp-rs/espup/tree/v0.2.1#install-subcommand)

I understand it's a bit confusing that the default documentation (`main` branch) is not aligned with the one you are seeing on your `--help` but we decided to update the name of this argument. Anyway, today I will publish `v0.2.2` and if you update it, they will be aligned.
