### ISSUE TITLE
Windows: Install MSVC dependency for x86_64-pc-windows-msvc

### ISSUE THREAD

**Issue by georgik** [esp-rs/espup#9]
Install MSVC dependency for x86_64-pc-windows-msvc.

Without this dependency, the user will get an error during builds like:
```
error: linker `link.exe` not found
  |
  = note: program not found

Note: the msvc targets depend on the msvc linker, but `link.exe` was not found

Note: please ensure that VS 2013, VS 2015, VS 2017, VS 2019, or VS 2022 was installed with the Visual C++ option
```

### How to simulate

Run the following command in Windows Sandbox:

```
 .\espup.exe install
```

### Solution

Implemented here: https://github.com/espressif/idf-env/blob/main/src/rust.rs#L335

The following command installs required dependencies:
```
vs_BuildTools.exe --passive --wait --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.20348
```

This command should be deployed before any `cargo install` takes place.

**Comment by SergioGasquez** [comment]
As discussed in #154, `espup` won't take care of installing this dependency.
